dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: test-decide-ci
  strategy: git
  api_key:
    secure: ApklzTjYKTUTFqQfojn95+oIpeNHPUwRTw9vQnoTkYQ8ibrg/3DCc3V0ck/eOnbmlJKvmPGiql/yyQOj7EOeui8tVQQlJQk8StOBJ/UePdaIg1TWzf5+FcKTIXamE0uK7RKco3iXTwR6QotCNGa7x5m6V9OQQSJlrT5ooQJT1Jt09+aFGaGJMGgRSWHkyxxM0ul9szhRMZHb7/22I51E3/7lyZk8lqlzxuwfpsU0Ytg98chfhmXy0eyYvRF2hIwa4lHuQcISqGQeQFRiHcl0qrTLiDFHe0NX6/KMe+aWl+6LpCrxlLbWXqHQ3UfQ+KoYCvjA7IBU5doMeb1VAPG+5EHtTUPsM8tNPVpTxtHFPmvpFWudSMzjPI0tNLqdZnOtiAPkN6LhXo+9VBO+hQW/Q0XEFTQf6COZ8+ebe6jJnAs7V+asJQ3AVC8SE+kbLVGsQqNNLZnsCcYQ7bY33dYr5759Idj4ZkV1VZ2cgiKG1rpqXXySyNBc3+NXYdw+D5qGhmVRKTtQ6t2scrEcOre4FqG9RwnhKxJJ8pWdai7cyKu/YLGe65rvnEWGb0Kav22EyhtL7Ppgwx13+UYFXWpEjE1d+cRJL8dCNQp00muDq3x5JbZluA2f6VfAWZH7KnALWiCeJD7uekR91CLnmz03YZ4hA2qyoxi+Y13gZGqkTgE=
